CREATE OR REPLACE FUNCTION archive.build_table_ddl(table_name text, schema_name text DEFAULT 'public'::text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_table_oid oid;
  v_cols text;
  v_constraints text;
  v_body text;
  v_indexes text;
  v_triggers text;
  v_policies text;
  v_rls_enabled boolean;
  v_rls_forced boolean;
  v_ddl text;
BEGIN
  SELECT c.oid, c.relrowsecurity, c.relforcerowsecurity
  INTO v_table_oid, v_rls_enabled, v_rls_forced
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = build_table_ddl.schema_name
    AND c.relname = build_table_ddl.table_name
    AND c.relkind IN ('r', 'p');

  IF v_table_oid IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT string_agg(col_def, E',\n  ' ORDER BY attnum)
  INTO v_cols
  FROM (
    SELECT
      a.attnum,
      format(
        '%I %s%s%s%s',
        a.attname,
        format_type(a.atttypid, a.atttypmod),
        CASE
          WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
          WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
          ELSE ''
        END,
        CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
        CASE
          WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
          ELSE ''
        END
      ) AS col_def
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = v_table_oid
      AND a.attnum > 0
      AND NOT a.attisdropped
  ) cols;

  SELECT string_agg(
    format('CONSTRAINT %I %s', conname, pg_get_constraintdef(oid, true)),
    E',\n  '
    ORDER BY conname
  )
  INTO v_constraints
  FROM pg_constraint
  WHERE conrelid = v_table_oid
    AND contype IN ('p', 'u', 'c', 'f', 'x');

  v_body := v_cols;
  IF v_constraints IS NOT NULL AND v_constraints <> '' THEN
    v_body := v_body || E',\n  ' || v_constraints;
  END IF;

  v_ddl := format(E'CREATE TABLE %I.%I (\n  %s\n);\n', build_table_ddl.schema_name, build_table_ddl.table_name, v_body);

  SELECT string_agg(pg_get_indexdef(i.indexrelid), E';\n')
  INTO v_indexes
  FROM pg_index i
  WHERE i.indrelid = v_table_oid
    AND NOT i.indisprimary
    AND NOT EXISTS (
      SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid
    );

  IF v_indexes IS NOT NULL AND v_indexes <> '' THEN
    v_ddl := v_ddl || v_indexes || E';\n';
  END IF;

  SELECT string_agg(pg_get_triggerdef(t.oid), E';\n')
  INTO v_triggers
  FROM pg_trigger t
  WHERE t.tgrelid = v_table_oid
    AND NOT t.tgisinternal;

  IF v_triggers IS NOT NULL AND v_triggers <> '' THEN
    v_ddl := v_ddl || v_triggers || E';\n';
  END IF;

  IF v_rls_enabled THEN
    v_ddl := v_ddl || format(E'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;\n', build_table_ddl.schema_name, build_table_ddl.table_name);
  END IF;

  IF v_rls_forced THEN
    v_ddl := v_ddl || format(E'ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;\n', build_table_ddl.schema_name, build_table_ddl.table_name);
  END IF;

  SELECT string_agg(policy_def, E';\n')
  INTO v_policies
  FROM (
    SELECT
      format(
        'CREATE POLICY %I ON %I.%I%s TO %s%s%s',
        pol.polname,
        build_table_ddl.schema_name,
        build_table_ddl.table_name,
        CASE pol.polcmd
          WHEN 'r' THEN ' FOR SELECT'
          WHEN 'a' THEN ' FOR INSERT'
          WHEN 'w' THEN ' FOR UPDATE'
          WHEN 'd' THEN ' FOR DELETE'
          WHEN '*' THEN ''
          ELSE ''
        END,
        CASE
          WHEN array_length(pol.polroles, 1) IS NULL THEN 'PUBLIC'
          ELSE (
            SELECT string_agg(quote_ident(r.rolname), ', ')
            FROM pg_roles r
            WHERE r.oid = ANY(pol.polroles)
          )
        END,
        CASE WHEN pol.polqual IS NOT NULL THEN ' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')' ELSE '' END,
        CASE WHEN pol.polwithcheck IS NOT NULL THEN ' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')' ELSE '' END
      ) AS policy_def
    FROM pg_policy pol
    WHERE pol.polrelid = v_table_oid
  ) policies;

  IF v_policies IS NOT NULL AND v_policies <> '' THEN
    v_ddl := v_ddl || v_policies || E';\n';
  END IF;

  RETURN v_ddl;
END;
$function$;
